[package]
name = "test_bincode"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
hex = "0.4"

[[bin]]
name = "test_rust_bincode"
path = "test_rust_bincode.rs"
